# Site
name: "Richard Lopes"
title: "Richard Lopes"
description: "Blog técnico, algumas coisas aleatórias e um pouco de mim"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: richardcruzlopes@gmail.com
url: "https://blog.riti.dev.br" # the base hostname & protocol for your site, e.g. http://example.com
domain: riti.dev.br
twitter_username: ritizera
github_username:  iRitiLopes

# Authors
authors:
  richard:
    name: Richard Lopes
    display_name: Richard Lopes
    gravatar: 9a5c4a5c67d5488cdc5fa03d7b0ad415
    email: richardcruzlopes@gmail.com
    web: links.riti.dev.br
    bluesky: https://bsky.app/profile/riti.dev.br
    description: "Engenheiro de Software Backend"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      bold_every: 5
      start_line: 1
      start_col: 2

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
